version: '2'
services:
    optimizationeventsjob-app:
        image: optimizationeventsjob
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://optimizationeventsjob-mysql:3306/optimizationeventsjob?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    optimizationeventsjob-mysql:
        extends:
            file: mysql.yml
            service: optimizationeventsjob-mysql
